// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCreator.Data;

namespace MovieCreator.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("MovieCreator.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<bool?>("isFinished")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "My favorite movie",
                            Name = "Shawshank Redemption",
                            Rating = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Stupidly funny",
                            Name = "Weekend at Bernies",
                            Rating = 8.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Interesting movie",
                            Name = "The Matrix",
                            Rating = 9.0999999999999996
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lot of classic jokes",
                            Name = "Airplane!",
                            Rating = 8.6999999999999993
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
